// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UUySKlFNRnpwQMG9ER01WZJ7JYSmYDw',
    appId: '1:442497912081:web:4c7af34960f7c00da790b0',
    messagingSenderId: '442497912081',
    projectId: 'spotify-clone-bee2a',
    authDomain: 'spotify-clone-bee2a.firebaseapp.com',
    storageBucket: 'spotify-clone-bee2a.firebasestorage.app',
    measurementId: 'G-E32EZS8Q2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp29WYoFUM-cWJaFGdk-Zgn3woFpdjnVc',
    appId: '1:442497912081:android:69b14b8b72e69e4aa790b0',
    messagingSenderId: '442497912081',
    projectId: 'spotify-clone-bee2a',
    storageBucket: 'spotify-clone-bee2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNHJj71qDUzmt2Y_xyuhrTqa3emqSdkFs',
    appId: '1:442497912081:ios:f9bc37c8c0ae8f9aa790b0',
    messagingSenderId: '442497912081',
    projectId: 'spotify-clone-bee2a',
    storageBucket: 'spotify-clone-bee2a.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNHJj71qDUzmt2Y_xyuhrTqa3emqSdkFs',
    appId: '1:442497912081:ios:f9bc37c8c0ae8f9aa790b0',
    messagingSenderId: '442497912081',
    projectId: 'spotify-clone-bee2a',
    storageBucket: 'spotify-clone-bee2a.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5UUySKlFNRnpwQMG9ER01WZJ7JYSmYDw',
    appId: '1:442497912081:web:0acdb4d26cc234f8a790b0',
    messagingSenderId: '442497912081',
    projectId: 'spotify-clone-bee2a',
    authDomain: 'spotify-clone-bee2a.firebaseapp.com',
    storageBucket: 'spotify-clone-bee2a.firebasestorage.app',
    measurementId: 'G-J6NX2JE5LJ',
  );
}
